project:
  type: website

website:
  title: "Data Science Summer Workshop 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - schedule.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

