---
title: "Schedule & Materials"
---

## Location

MAG B2-52

## Dates & Times

### Wednesday, Jan 18, 2023

#### 12 -- 2 pm

-   Welcome and introduction ("What is data science?")
-   First steps with R
    -   [slides](slides/d01_01_welcome.html){target="_blank"}
    -   [pdf](slides/d01_01_welcome.pdf){target="_blank"}

#### 2:30 -- 5 pm

-   Basic data exploration and visualisation
-   A reproducible workflow with Quarto
    -   [slides](slides/d01_02_data_exploration_basics.html){target="_blank"}
    -   [pdf](slides/d01_02_basic_data_exploration.pdf){target="_blank"}

### Thursday, Jan 19, 2023

#### 10:00 am -- 12:30 pm

-   More on R
-   Data visualisation (ctd.)
    -   [slides](slides/d02_03_data_exploration2.html){target="_blank"}
    -   [pdf](slides/d02_03_data_exploration2.pdf){target="_blank"}

#### 1:30 -- 3 pm

-   Practise your skills!

#### 3:30 -- 5 pm

-   Customising Quarto documents (and figures if we have time)
    -   [html](slides/d02_04_quarto.html){target="_blank"}
-   Installing R and RStudio on your own computer
    -   [slides](slides/d02_05_installing_R.html){target="_blank"}
    -   [pdf](slides/d02_05_installing_R.pdf){target="_blank"}

### Friday, Jan 20, 2023

#### 10:00 am -- 12:30 pm

-   Importing data 
    -   [slides](slides/d03_06a_importing_data.html){target="_blank"}
    -   [pdf](slides/d03_06a_importing.pdf){target="_blank"}
-   Tidying data
    -   [slides](slides/d03_06b_tidying_data.html){target="_blank"}
    -   [pdf](slides/d03_06b_tidying.pdf){target="_blank"}
-   A bit more on customising figures

#### 1:30 -- 3:00 pm

-   Working with text ("strings")

#### 3:30 -- 5:00 pm

-   Version control with git and GitHub

## Resources
-   [zip archive](resources/data_sci_resources.zip) of files that we will be using